# Generated by Django 5.2.4 on 2025-07-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
